AWSTemplateFormatVersion: '2010-09-09'
Description: SAM template for deploying ECS Automation
Transform: AWS::Serverless-2016-10-31
Resources:
  IAMRoleForECSAutomation:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com  
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: MyPolicy  
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow  
                Action:
                  - s3:GetObject  
                  - s3:PutObject  
                Resource: "*" 


  modelRegistryList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-list-model-registry
      Handler: list-registry.lambda_handler
      Runtime: python3.9
      CodeUri: functions/list-registry
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90

  modelRegistry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-model-registry
      Handler: model-registry.lambda_handler
      Runtime: python3.9
      CodeUri: functions/model-registry
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90

  createASG:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-create-ec2-asg
      Handler: create-asg.lambda_handler
      Runtime: python3.9
      CodeUri: functions/create-auto-scaling-group
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
  

  deployECS:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-deploy-ecs-service
      Handler: create-ecs-service.lambda_handler
      Runtime: python3.9
      CodeUri: functions/create-ecs-service
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
  
  createTaskCluster:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-deploy-ecs-service
      Handler: create-ecs-task.lambda_handler
      Runtime: python3.9
      CodeUri: functions/create-task-cluster
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90

  createTargetListners:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-deploy-ecs-service
      Handler: target-groups.lambda_handler
      Runtime: python3.9
      CodeUri: functions/load-balancer
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90

  rollback:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-deploy-ecs-service
      Handler: rollback.lambda_handler
      Runtime: python3.9
      CodeUri: functions/Rollback
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90