AWSTemplateFormatVersion: '2010-09-09'
Description: SAM template for deploying ECS Automation framework
Transform: AWS::Serverless-2016-10-31
Parameters:
  accountid:
    Type: String
    Description: AWS Account ID for dev, qa, Prod 
  region:
    Type: String
    Description: AWS Region where code need to be deployed
  vpc:
    Type: String
    Description: VPC ID for Load Balancer and ASG
  subnets:
    Type: String
    Description: subnets for Load Balancer and ASG
  x86:
    Type: String
    Description: EC2 AMI ID for X86 processor 
  arm: 
    Type: String  
    Description: EC2 AMI ID for ARM processor 
  imageID:
    Type: String
    Description: EC2 Image id
  mlopsS3BucketName:
    Type: String  
    Description: S3 bucket for storing model artifcats 

Resources:

  mlopsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ec2-instance-role
      Roles:
        - !Ref instanceRole

  instanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: mlops-ecs-ec2
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
            - Effect: "Allow"
              Action: 
              - "ssm:StartSession"
              - "ec2:DescribeInstances"
              Resource: "*"
            - Effect: "Allow"
              Action: 
              - "ecs:CreateCluster"
              - "ecs:DeregisterContainerInstance"
              - "ecs:DiscoverPollEndpoint"
              - "ecs:Poll"
              - "ecs:RegisterContainerInstance"
              - "ecs:StartTelemetrySession"
              - "ecs:Submit*"
              - "ecs:DescribeServices"
              - "ecs:DescribeTasks"
              - "ecs:DescribeClusters"
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              Resource: "*"
  
  IAMRoleForECSdelete:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mlops-delete-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: mlops-delete
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - ec2:DeleteLaunchTemplate
              - dynamodb:GetItem
              - ecs:DeleteService
              - dynamodb:UpdateItem
              - autoscaling:DeleteAutoScalingGroup
              - ec2:DeleteLaunchTemplateVersions
              Resource:
              - arn:aws:ecs:*:270932919550:service/mlops-*/*
              - arn:aws:dynamodb:*:270932919550:table/mlops-*
              - arn:aws:autoscaling:*:270932919550:autoScalingGroup:*:autoScalingGroupName/mlops-*
              - arn:aws:ec2:*:270932919550:launch-template/*
            - Effect: Allow
              Action:
              - elasticloadbalancing:DeleteTargetGroup
              - elasticloadbalancing:DeleteRule
              - elasticloadbalancing:DeleteListener
              Resource: "*"


  IAMRoleForECSAutomation:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mlops-ecs-automation
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ec2.amazonaws.com
                - ecr.amazonaws.com
                - ecs-tasks.amazonaws.com  
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: mlops-dynamodb  
          PolicyDocument:
           Version: '2012-10-17'
           Statement:
            - Effect: Allow
              Action: 
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !Sub 'arn:aws:dynamodb:${region}:${accountid}:table/mlops-*'

        - PolicyName: mlops-ec2  
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:DescribeLaunchTemplates'
                  - 'ec2:DescribeTags'
                  - 'ec2:CreateTags'
                  - 'ec2:DescribeLaunchTemplateVersions'
                  - 'ec2:RunInstances'
                  - 'ssm:GetParameters'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:CreateLaunchTemplateVersion'
                  - 'ec2:GetLaunchTemplateData'
                  - 'ec2:CreateLaunchTemplate'
                  - 'ec2:DescribeInstanceTypeOfferings'
                  - 'ec2:DescribeInstanceTypes'
                  - 'ec2:DescribeSubnets'
                  - 'autoscaling:CreateAutoScalingGroup'
                  - 'autoscaling:UpdateAutoScalingGroup'
                  - 'ec2:DescribeInstanceStatus'
                  - 'autoscaling:DescribeAutoScalingGroups'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                  - 'iam:CreateServiceLinkedRole'
                Resource: '*'

        - PolicyName: mlops-ecr 
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'ecr:BatchCheckLayerAvailability'
                Resource: !Sub 'arn:aws:ecr:${region}:${accountid}:repository/*'
              - Effect: Allow
                Action: 'ecr:GetAuthorizationToken'
                Resource: '*'

        - PolicyName: mlops-ecs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:CreateCluster'
                  - 'ecs:TagResource'
                  - 'ecs:ListClusters'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ecs:RegisterTaskDefinition'
                  - 'logs:CreateLogGroup'
                Resource:
                  - !Sub 'arn:aws:ecs:${region}:${accountid}:task-definition/mlops-*:*'
                  - !Sub 'arn:aws:logs:${region}:${accountid}:log-group:mlops-*'
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action: 'ecs:CreateService'
                Resource: '*'
              - Effect: Allow
                Action: 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${region}:${accountid}:log-group:mlops-*:log-stream:mlops-*'

        - PolicyName: mlops-elb 
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:RegisterTargets'
                  - 'elasticloadbalancing:CreateTargetGroup'
                  - 'elasticloadbalancing:ModifyTargetGroup'
                Resource: !Sub 'arn:aws:elasticloadbalancing:${region}:${accountid}:targetgroup/*/*'
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:CreateListener'
                  - 'elasticloadbalancing:DescribeListeners'
                  - 'elasticloadbalancing:AddTags'
                  - 'elasticloadbalancing:DescribeTargetGroups'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:RegisterTargets'
                  - 'elasticloadbalancing:CreateTargetGroup'
                  - 'elasticloadbalancing:ModifyTargetGroup'
                Resource: !Sub 'arn:aws:elasticloadbalancing:${region}:${accountid}:targetgroup/*/*'


        - PolicyName: mlops-lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - 'lambda:InvokeFunctionUrl'
                  - 'lambda:InvokeFunction'
                Resource: !Sub 'arn:aws:lambda:${region}:${accountid}:function:mlops-*'
              - Effect: Allow
                Action: 'logs:CreateLogGroup'
                Resource: !Sub 'arn:aws:logs:${region}:${accountid}:*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'


  albSecurituGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref vpc
      GroupDescription: My security group description
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 6000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0

  mlopsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      SecurityGroups: [!Ref albSecurituGroup]
      Subnets: !Split
        - ","
        - !Ref subnets

  mlopsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref mlopsS3BucketName
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'


  mlopsDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mlops-model-registry
      AttributeDefinitions:
        - AttributeName: registry-name
          AttributeType: S
        # Add more attribute definitions as needed
      KeySchema:
        - AttributeName: registry-name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  modelRegistryList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-list-model-registry
      Handler: list-registry.lambda_handler
      Runtime: python3.9
      CodeUri: functions/list-registry
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90

  modelRegistry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-model-registry
      Handler: model-registry.lambda_handler
      Runtime: python3.9
      CodeUri: functions/model-registry
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90

  createASG:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-create-ec2-asg
      Handler: create-asg.lambda_handler
      Runtime: python3.9
      CodeUri: functions/create-auto-scaling-group
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
      Environment:
        Variables:
          AMI_ARM: !Ref arm
          AMI_x86: !Ref x86
          ARN: !GetAtt mlopsInstanceProfile.Arn
          bool: "True"
          AMI_ID: !Ref imageID
          SUBNETS: !Ref subnets
  

  deployECS:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-deploy-ecs-service
      Handler: create-ecs-service.lambda_handler
      Runtime: python3.9
      CodeUri: functions/create-ecs-service
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
      Environment:
        Variables:
          SUBNETS: !Ref subnets
          SG: !Ref albSecurituGroup
  
  createTaskCluster:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-create-ecs-task
      Handler: create-ecs-task.lambda_handler
      Runtime: python3.9
      CodeUri: functions/create-task-cluster
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
      Environment:
        Variables:
          TABLE_NAME: !Ref mlopsDynamoDB

  createTargetListners:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-target-listners-lb
      Handler: target-groups.lambda_handler
      Runtime: python3.9
      CodeUri: functions/load-balancer
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
      Environment:
        Variables:
          LOADBALANCER_ARN: !Ref mlopsLoadBalancer
          TABLE_NAME: !Ref mlopsDynamoDB
          VPC: !Ref vpc

  updateDynamoSuccess:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-update-dynamo-success
      Handler: update-dynamo.lambda_handler
      Runtime: python3.9
      CodeUri: functions/dynamo-db-success
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
      Environment:
        Variables:
          LOADBALANCER_NAME: !GetAtt mlopsLoadBalancer.DNSName
          TABLE_NAME: !Ref mlopsDynamoDB

  rollback:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-rollback
      Handler: rollback.lambda_handler
      Runtime: python3.9
      CodeUri: functions/Rollback
      Role: !GetAtt 
        - IAMRoleForECSAutomation
        - Arn
      Timeout: 90
  
  deleteMLOPS:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-delete
      Handler: delete-mlops.lambda_handler
      Runtime: python3.9
      CodeUri: functions/delete-mlops
      Role: !GetAtt 
        - IAMRoleForECSdelete
        - Arn
      Timeout: 90
      Environment:
        Variables:
          TABLE_NAME: !Ref mlopsDynamoDB

  sendEmail:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-send-email
      Handler: send-email.lambda_handler
      Runtime: python3.9
      CodeUri: functions/send-success-email
      Role: !GetAtt 
        - IAMRoleForECSdelete
        - Arn
      Timeout: 90
      Environment:
        Variables:
          LOADBALANCER_NAME: !GetAtt mlopsLoadBalancer.DNSName
  
  checkServiceStatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-check-ecs-service-status
      Handler: check-deployment-status.lambda_handler
      Runtime: python3.9
      CodeUri: functions/check-deployment-status
      Role: !GetAtt 
        - IAMRoleForECSdelete
        - Arn
      Timeout: 90
      Environment:
        Variables:
          LOADBALANCER_NAME: !GetAtt mlopsLoadBalancer.DNSName

  ecsAutomationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
       Name: ecs-automation-statemachine
       DefinitionUri: stepfunctions/ecs-automation.asl.json
       DefinitionSubstitutions:
          create-target-listner: !GetAtt createTargetListners.Arn
          rollback: !GetAtt rollback.Arn
          create-ecs-clusters: !GetAtt createTaskCluster.Arn
          create-auto-scaling: !GetAtt createASG.Arn
          deploy-ecs-task: !GetAtt deployECS.Arn
          mlops-update-dynamo-success: !GetAtt updateDynamoSuccess.Arn
          send-success-email: !GetAtt sendEmail.Arn
       Role: !GetAtt 
            - IAMRoleForECSAutomation
            - Arn
